

CREATE DATABASE IF NOT EXISTS autores;
CREATE DATABASE IF NOT EXISTS generos;
CREATE DATABASE IF NOT EXISTS libros;
CREATE DATABASE IF NOT EXISTS nombres;
CREATE DATABASE IF NOT EXISTS domicilios;
CREATE DATABASE IF NOT EXISTS usuarios;
CREATE DATABASE IF NOT EXISTS bibliotecario;
CREATE DATABASE IF NOT EXISTS turnos;
CREATE DATABASE IF NOT EXISTS bodegas;
CREATE DATABASE IF NOT EXISTS estantes;